#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

# Install and run Ansible

distribution=$(lsb_release -si)

if [ "$distribution" = "Debian" ]; then
	echo "Installing Ansible with apt"
	sudo apt update && sudo apt install ansible
else
	echo "Installing Ansible with pamac"
	pamac install ansible
fi

echo "Running Ansible Playbooks"
ansible-playbook ~/ansible/basic.yml -K -i ansible_hosts
ansible-playbook ~/ansible/users.yml -K -i ansible_hosts
ansible-playbook ~/ansible/desktop.yml -K -i ansible_hosts

# Init git and yadm submodules
git init

echo "Init and update tpm"
~/bin/yadm submodule init ".tmux/plugins/tpm"
~/bin/yadm submodule update --remote --merge  ".tmux/plugins/tpm"

echo "Install tmux plugins via tpm"
tmux start-server
~/.tmux/plugins/tpm/bin/install_plugins

echo "Init yadm submodules"
~/bin/yadm submodule update --recursive --init

echo "Remote merge yadm submodules"
~/bin/yadm submodule update --remote --merge

echo "Init git submodules"
git submodule update --recursive --init

# Install VIM plugins defined in .vimrc

echo "Install VIM plugins via Vundle"
vim +PluginInstall +qall

echo "DONE"
