#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init yadm submodules"
yadm submodule update --recursive --init

echo "Init git submodules"
git submodule update --recursive --init

echo "Install VIM plugins via Vundle"
vim +PluginInstall +qall
