---
- hosts: localhost
  become: yes
  tasks:
    - name: install desktop packages
      package:
        name: "{{ item}}"
        state: present
      loop:
        - thunderbird
        - pdfsam
        - neovim-qt

    - name: install Firefox from the flathub repository
      flatpak:
        name: org.mozilla.firefox
        state: present
        remote: flathub
        method: user
  
    - name: Permit Flatpak Firefox to use ~/.mozilla
      shell: flatpak override --user --filesystem="$HOME/.mozilla" org.mozilla.firefox
      args:
        chdir: $HOME
        executable: /bin/bash
