---
- hosts: localhost
  become: yes
  tasks:
    - name: install networking tools packages
      package:
        name: "{{ item}}"
        state: present
      loop:
        - zenmap
        - wireshark
        - tcpdump
